### ISSUE TITLE
is it supposed to say errors

### ISSUE THREAD

**Issue by 2pgk** [Luckytrang2010/BrutePin#3]
![Screenshot_159](https://user-images.githubusercontent.com/64868100/110164211-f4549280-7de8-11eb-9374-efbe7401fe50.png)

**Comment by Luckytrang2010** [comment]
did you get the right cookie?

**Comment by 2pgk** [comment]
yea

**Comment by Luckytrang2010** [comment]
if so then can you show me what you did to get the cookie out of?

**Comment by 2pgk** [comment]
i got it from Application>Cookies and then found .ROBLOSECURITY

**Comment by 2pgk** [comment]
![Screenshot_160](https://user-images.githubusercontent.com/64868100/110164685-9e341f00-7de9-11eb-9844-f16313ad4165.png)

**Comment by Luckytrang2010** [comment]
nono thats not how you do it

**Comment by 2pgk** [comment]
oh

**Comment by Luckytrang2010** [comment]
you get the cookie header out of this
![image](https://user-images.githubusercontent.com/53712708/110164808-e4748880-7dbf-11eb-99a5-acbbaa3c807f.png)

**Comment by Luckytrang2010** [comment]
sorry if i confused you by saying ROBLOSECURITY in the readme.md

**Comment by 2pgk** [comment]
oh nvm i got it

but it says too many requests please wait

**Comment by Luckytrang2010** [comment]
yeah thats normal, you just gotta wait which sucks

**Comment by 2pgk** [comment]
how long does it usually take?

**Comment by Luckytrang2010** [comment]
not sure but you can wait 5 minutes or so to cool down the limit
